export const PLANS = {
  FREE: {
    name: "Free",
    price: 0,
    yearly: true,
    maxTasksPerMonth: 100,
  },
  'PRO-MONTHLY': {
    name: "Pro",
    price: 3,
    discountedPrice: 2,
    yearly: false,
    maxTasksPerMonth: -1,
    features: [
      "Search emails to unsubscribe by sender and content",
      "Advanced email analysis with charts and statistics",
      "Scheduled email fetching (coming soon)",
    ],
  },
  'PRO-YEARLY': {
    name: "Pro",
    price: 24,
    discountedPrice: 16,
    yearly: true,
    maxTasksPerMonth: -1,
    features: [
      "Search emails to unsubscribe by sender and content",
      "Advanced email analysis with charts and statistics",
      "Scheduled email fetching (coming soon)",
    ],
  },
};

export const QUOTES = [
  "Just ship it.",
  "Rise above every setback.",
  "Keep moving, even when the path is steep.",
  "Strength lies in the heart that never quits.",
  "Every challenge is a new opportunity to grow.",
  "Breathe, adapt, and keep pushing forward.",
  "Small steps can lead to great heights.",
  "Don’t stop now, you’re closer than you think.",
  "Embrace the struggle. It shapes you.",
  "Keep the flame burning, no matter the storm.",
  "Progress is built on persistence.",
  "When it’s hard, that’s when it matters most.",
  "Endure the trials, for they mold the strongest souls.",
  "Keep your head high and your spirit unbroken.",
  "The climb is tough, but the view is worth it.",
  "Let each fall fuel your next rise.",
  "Hold on. The best chapters come after the hardest battles.",
  "Push beyond limits, for there’s more within you.",
  "Each day is a new chance to keep going.",
  "Turn every 'no' into your drive to succeed.",
  "Storms may come, but you can weather them all.",
  "Stay steady, even when the road bends.",
  "Let nothing dim the light inside you.",
  "Perseverance is the path to the summit.",
  "Keep striving. The world hasn’t seen your best yet.",
  "Your strength is your superpower.",
  "In every challenge lies a hidden gift.",
  "Great things take time. Keep building.",
  "Courage isn’t the absence of fear, but action despite it.",
  "Push through the walls that stand in your way.",
  "Endurance turns dreams into reality."
];
